# Generated by Django 2.2.6 on 2019-11-01 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_password', models.CharField(max_length=50)),
                ('customer_number', models.CharField(max_length=50)),
                ('customer_blance', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_no', models.IntegerField()),
                ('dept_name', models.CharField(max_length=50)),
                ('dept_code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Regiest_Form',
            fields=[
                ('std_num', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('std_name', models.CharField(max_length=50)),
                ('std_deptart', models.CharField(max_length=50)),
                ('year_fees', models.CharField(max_length=50)),
                ('std_year', models.CharField(max_length=50)),
                ('std_sem', models.CharField(max_length=50)),
                ('std_type_to_regiest', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_password', models.CharField(max_length=50)),
                ('transaction_date', models.DateTimeField(auto_now=True)),
                ('sender_account_number', models.CharField(max_length=50)),
                ('reciver_account_number', models.CharField(max_length=50)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('customer_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project_app.Customer_Profile')),
            ],
        ),
    ]
