# Generated by Django 2.2.6 on 2019-12-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_profile',
            name='customer_blance',
        ),
        migrations.AddField(
            model_name='transaction',
            name='customer_blance',
            field=models.DecimalField(decimal_places=2, default=5.5, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='register_fees',
            field=models.DecimalField(decimal_places=2, default=5.5, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='university_blance',
            field=models.DecimalField(decimal_places=2, default=5.5, max_digits=8),
            preserve_default=False,
        ),
    ]
