# Generated by Django 2.2.6 on 2019-12-24 08:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0002_auto_20191224_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_profile',
            name='customer_blance',
            field=models.DecimalField(decimal_places=2, default=5.5, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
