# Generated by Django 2.2.6 on 2019-12-25 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0003_auto_20191224_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='regiest_form',
            name='register_fees',
            field=models.FloatField(default=5.5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer_profile',
            name='customer_blance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='regiest_form',
            name='year_fees',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='customer_blance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='register_fees',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='university_blance',
            field=models.FloatField(),
        ),
    ]
