# Generated by Django 2.2.6 on 2019-12-25 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0004_auto_20191225_0812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regiest_form',
            name='std_deptart',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='customer_blance',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='customer_password',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='register_fees',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='university_blance',
        ),
        migrations.AddField(
            model_name='customer_profile',
            name='university_blance',
            field=models.FloatField(default=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer_profile',
            name='university_number',
            field=models.CharField(default=12345, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regiest_form',
            name='deptartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_app.Department'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_app.Customer_Profile'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_app.Regiest_Form'),
        ),
    ]
