# Generated by Django 2.2.6 on 2019-12-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0006_auto_20191226_0801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regiest_form',
            name='deptartment',
        ),
        migrations.AddField(
            model_name='regiest_form',
            name='department',
            field=models.ManyToManyField(to='project_app.Department'),
        ),
    ]
